### ISSUE TITLE
Add a switch to freeze the shape

### ISSUE THREAD

**Issue by ev-br** [ev-br/sparr#36]
Once frozen, out-of-bounds get/set_item raises an IndexError.

**Comment by ev-br** [comment]
One option is to switch it on if the shape is given in the constructor. Tgis seems too magical --- the default should likely be just False, and a T/F property to toggle it.

**Comment by shoyer** [comment]
I like switching if if the shape is given in the constructor. I don't see other good reasons for providing the shape explicitly.

**Comment by ev-br** [comment]
Done in gh-38, closing.
